#!/bin/bash

version="2.68.1"
conflicts=("fastfetch")
depends=("glibc" "tar")

install() {
    rm -f fastfetch-linux-amd64.tar.gz
    wget https://github.com/fastfetch-cli/fastfetch/releases/download/$version/fastfetch-linux-amd64.tar.gz
    rm -rf fastfetch/
    mkdir -p fastfetch/
    tar -xf fastfetch-linux-amd64.tar.gz -C fastfetch --strip-components=1
    cd fastfetch/
    cp -rf usr/bin/fastfetch /usr/bin/fastfetch
}

remove() {
    rm /usr/bin/fastfetch
}
