#!/bin/bash

version="1.13.2"
depends=("make" "gcc" "glibc" "tar" "python" "cmake||cmake-bin")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/ninja-build/ninja/archive/refs/tags/v$version.tar.gz
    rm -rf ninja/
    mkdir -p ninja/
    tar -xf v$version.tar.gz -C ninja --strip-components=1
    cd ninja/
    cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    cmake --build build
    cmake --install build
}

remove() {
    rm -f /usr/bin/ninja
    rm -f /usr/share/bash-completion/completions/ninja
    rm -f /usr/share/zsh/site-functions/_ninja
}
