#!/bin/bash

version="3.5.2"
depends=("make" "gcc" "glibc" "tar" "autoconf" "automake")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/libffi/libffi/archive/refs/tags/v$version.tar.gz
    rm -rf libffi/
    mkdir -p libffi/
    tar -xf v$version.tar.gz -C libffi --strip-components=1
    cd libffi/
    ./autogen.sh
    MAKEINFO=true ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib --disable-static
    MAKEINFO=true make
    MAKEINFO=true make install
}

remove() {
    cd libffi/
    make uninstall
}
