#!/bin/bash

version="1.1.45"
depends=("make" "gcc" "glibc" "zlib" "libxml2" "tar" "pkgconf")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/GNOME/libxslt/archive/refs/tags/v$version.tar.gz
    rm -rf libxslt/
    mkdir -p libxslt/
    tar -xf v$version.tar.gz -C libxslt --strip-components=1
    cd libxslt/
    CPPFLAGS="-I/usr/include/libxml2" ./autogen.sh prefix=/usr
    make
    make install
}

remove() {
    cd libxslt/
    make uninstall
}
