#!/bin/bash

version="0.6.0"
depends=("bash" "tar")

install() {
    rm -f $version.tar.gz
    wget https://github.com/dylanaraps/pfetch/archive/refs/tags/$version.tar.gz
    rm -rf pfetch/
    mkdir -p pfetch/
    tar -xf $version.tar.gz -C pfetch --strip-components=1
    cd pfetch/
    cp pfetch /usr/bin/
}

remove() {
    rm -f /usr/bin/pfetch
}
