#!/bin/bash

version="3.8.2"
depends=("m4" "make" "gcc" "glibc" "tar")

install() {
    rm -f bison-$version.tar.gz
    wget https://ftp.gnu.org/gnu/bison/bison-$version.tar.gz
    rm -rf bison/
    mkdir -p bison/
    tar -xf bison-$version.tar.gz -C bison --strip-components=1
    cd bison/
    ./configure --prefix=/usr
    make
    make install
}

remove() {
    cd bison/
    make uninstall
}
