#!/bin/bash

version="0.195"
depends=("make" "gcc" "glibc" "tar" "zlib" "pkgconf" "m4")

install() {
    rm -f elfutils-$version.tar.bz2
    wget https://sourceware.org/elfutils/ftp/$version/elfutils-$version.tar.bz2
    rm -rf elfutils/
    mkdir -p elfutils/
    tar -xf elfutils-$version.tar.bz2 -C elfutils --strip-components=1
    cd elfutils/
    export CFLAGS="${CFLAGS} -fPIE -fPIC -Wno-error"
    export CXXFLAGS="${CXXLAGS} -fPIE -fPIC -Wno-error"
    ./configure --prefix=/usr --sysconfdir=/etc --disable-werror
    make
    make install
}

remove() {
    cd elfutils/
    make uninstall
}
