#!/bin/bash

version="2.6.4"
depends=("m4" "make" "gcc" "glibc" "tar")

install() {
    rm -f flex-$version.tar.gz
    wget https://github.com/westes/flex/releases/download/v$version/flex-$version.tar.gz
    rm -rf flex/
    mkdir -p flex/
    tar -xf flex-$version.tar.gz -C flex --strip-components=1
    cd flex/
    LEX=: ./configure --prefix=/usr
    make
    make install
}

remove() {
    cd flex/
    make uninstall
}
