#!/bin/bash

version="1.5"
depends=("bash" "tar")

install() {
    rm -f $version.tar.gz
    wget https://github.com/Nick-cpp/nfetch/archive/refs/tags/$version.tar.gz
    rm -rf nfetch
    mkdir -p nfetch/
    tar -xf $version.tar.gz -C nfetch --strip-components=1
    cd nfetch/
    chmod +x nfetch
    cp nfetch /usr/bin/
}

remove() {
    rm /usr/bin/nfetch
}
