#!/bin/bash

version="1.9.4"
depends=("python" "make" "busybox" "ncurses" "gcc" "glibc" "python-setuptools")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/ranger/ranger/archive/refs/tags/v$version.tar.gz
    rm -rf ranger/
    mkdir -p ranger/
    tar -xf v$version.tar.gz -C ranger --strip-components=1
    cd ./ranger
    python setup.py install --optimize=1 --record=install_log.txt
}

remove() {
    if [ -f ranger/install_log.txt ]; then
        cd ranger/
        xargs rm -rf < install_log.txt
    fi
}
