#!/bin/bash

version="1.19"
depends=("make" "gcc" "glibc" "tar")

install() {
    rm -f popt-$version.tar.gz
    wget https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-$version.tar.gz
    rm -rf popt/
    mkdir -p popt/
    tar -xf popt-$version.tar.gz -C popt --strip-components=1
    cd popt/
    ./configure --prefix=/usr --disable-static
    make
    make install
}

remove() {
    cd popt/
    make uninstall
}
