#!/bin/bash

version="1.3.2"
depends=("make" "gcc" "glibc" "tar")

install() {
    rm -f zlib-$version.tar.gz
    wget https://github.com/madler/zlib/releases/download/v$version/zlib-$version.tar.gz
    rm -rf zlib/
    mkdir -p zlib/
    tar -xf zlib-$version.tar.gz -C zlib --strip-components=1
    cd zlib/
    ./configure
    make prefix=/usr
    make install prefix=/usr
}

remove() {
    cd zlib/
    make uninstall prefix=/usr
}
